AmooJozveForoosh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('apps.landpage.urls', namespace='landpage')),
    url(r'^admin/', admin.site.urls),
    url(r'^advertise/', include('apps.advertise.urls')),
    url(r'^profiles/', include('apps.profiles.urls')),
    url(r'^cart/', include('apps.carts.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/advertise/urls.py
from django.conf.urls import url
from . import views

app_name = 'advertise'
urlpatterns = [
    url(r'^$', views.AdvertiseListView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', views.AdvertiseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.AddAdvertise.as_view(), name='add_advertise'),
    url(r'^(?P<pk>[0-9]+)/add-comment/$', views.CommentCreateView.as_view(), name='add_comment'),
    url(r'^ajax/filter-counties/$', views.filter_cities, name='filter-counties'),
    url(r'^rating/(?P<advertise_id>\d+)/$', views.rating, name='rating')
]

apps/carts/urls.py
from django.conf.urls import url
from . import views

app_name = 'carts'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.CartDetailView.as_view(), name='detail'),
    url(r'^add-to-cart/$', views.CartCreateView.as_view(), name='add_to_cart'),
    url(r'^remove-from-cart/$', views.CartRemoveView.as_view(), name='remove_from_cart'),
]

apps/advertise/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Province(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('Province name'))

    def __str__(self):
        return self.name


class County(models.Model):
    province = models.ForeignKey(Province, related_name="counties", verbose_name=_('Province'),
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=30, verbose_name=_('County name'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Counties'


class University(models.Model):
    county = models.ForeignKey(County, on_delete=models.CASCADE, verbose_name=_('County'),
                               related_name='universities')
    name = models.CharField(max_length=50, verbose_name=_('university name'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Universities'


class Advertise(models.Model):
    PUBLIC = 'P'
    MAJOR_CHOICES = (
        (PUBLIC, _('Public')),
        ('CE', _('Computer Engineering')),
        ('EE', _('Electrical Engineering')),
    )

    PENDING = 'P'
    PUBLISHED = 'PB'
    CLOSED = 'C'
    STATE_CHOICES = (
        (PENDING, _('Pending')),
        (PUBLISHED, _('Published')),
        (CLOSED, _('Closed')),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('User'))
    county = models.ForeignKey(County, on_delete=models.SET_NULL, null=True, verbose_name=_('County'))
    university = models.ForeignKey(University, on_delete=models.SET_NULL, verbose_name=_('University'),
                                   blank=True, null=True)
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    description = models.TextField(max_length=2000, verbose_name=_('Description'))
    expiration_date = models.DateTimeField(blank=True, null=True,
                                           verbose_name=_('Expiration date'))  # null = never expire
    price = models.PositiveIntegerField(verbose_name=_('Price'))
    major = models.CharField(max_length=10, choices=MAJOR_CHOICES, default=PUBLIC, verbose_name=_('Major'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))
    state = models.CharField(max_length=10, choices=STATE_CHOICES, default=PENDING, verbose_name=_('State'))
    page_numbers = models.PositiveIntegerField(null=True, blank=True, verbose_name=_('Page numbers'))
    publisher = models.CharField(max_length=100, null=True, blank=True, verbose_name=_('Publisher'))
    release_year = models.CharField(max_length=4, null=True, blank=True, verbose_name=_('Release year'))

    def __str__(self):
        return self.title


class AdvertiseImage(models.Model):
    ADVERTISE_IMAGE_UPLOAD_PATH = 'advertise/images'
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=ADVERTISE_IMAGE_UPLOAD_PATH, verbose_name=_('Advertise image'))

    def __str__(self):
        return self.advertise.title


class Comment(models.Model):
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='comments', null=True)
    text = models.TextField(verbose_name=_('Text'), max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    def approve(self):
        self.approved = True
        self.save()


class Rate(models.Model):
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.SmallIntegerField(validators=[MaxValueValidator(5)])

    def __str__(self):
        return "{} - {} - {}".format(self.advertise.title, self.user.email, self.rate)

apps/carts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from apps.advertise.models import Advertise

User = get_user_model()


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    advertises = models.ManyToManyField(Advertise, blank=True)

    def __str__(self):
        return self.user.email + "'s card"

apps/carts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView
from django.views.generic.base import View

from apps.advertise.models import Advertise
from apps.carts.models import Cart


class CartCreateView(View):
    def post(self, request, *args, **kwargs):
        user = self.request.user
        advertise_id = self.request.POST.get('ad_id')
        advertise = Advertise.objects.get(pk=advertise_id)
        cart = user.cart
        cart.advertises.add(advertise)
        return redirect('advertise:list')


class CartRemoveView(View):
    def post(self, request, *args, **kwargs):
        user = self.request.user
        advertise_id = self.request.POST.get('ad_id')
        advertise = Advertise.objects.get(pk=advertise_id)
        cart = user.cart
        cart.advertises.remove(advertise)
        return redirect(reverse('carts:detail', args=(cart.id,)))


class CartDetailView(LoginRequiredMixin, View):

    def get(self, request,  pk):
        template_name = 'carts/cart_detail.html'
        cart = get_object_or_404(Cart, id=pk)
        context = {'object': cart}
        if cart.user != self.request.user:
            raise Http404
        return render(request, template_name, context=context)

apps/carts/templates/carts/cart_detail.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load staticfiles %}
{% block body %}
    <div class="ui container">
        <h1 class="ui header">
            سبد خرید
        </h1>
        {% if object.advertises.all %}
            <div class="ui special cards">
                {% for advertise in object.advertises.all %}
                    {# things to show per advertise in cart #}
                    <div class="card">
                        <div class="blurring dimmable image">
                            <div class="ui dimmer">
                                <div class="content">
                                    <div class="center">
                                        <div class="ui inverted button">نمایش آگهی</div>
                                    </div>
                                </div>
                            </div>
                            <img src="{{ advertise.advertiseimage_set.first.image.url }}">
                        </div>
                        <div class="content">
                            <a class="header" href="{% url 'advertise:detail' advertise.id %}">{{ advertise.title }}</a>
                            <div class="meta">
                                {% if advertise.release_year %}
                                    <span class="date">{{ advertise.release_year }}</span>
                                {% endif %}
                            </div>
                        </div>
                        {# cart ui button add to cart #}
                        {% block card_section %}
                            <div class="extra content">
                                <form method="post" action="{% url 'carts:remove_from_cart' %}">{% csrf_token %}
                                    <input type="hidden" name="ad_id" value="{{ advertise.id }}">
                                    <button class="ui small icon button" type="submit">
                                        <i class="delete red icon"></i>
                                    </button>
                                </form>
                            </div>
                        {% endblock %}
                        {# end cart ui button #}
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="ui compact message">
                <p> سبد خرید شما خالی است</p>
                <p><a href="{% url 'advertise:list' %}" class="ui big green button">خرید</a></p>
            </div>
        {% endif %}
    </div>
{% endblock body %}