AmooJozveForoosh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('apps.landpage.urls', namespace='landpage')),
    url(r'^admin/', admin.site.urls),
    url(r'^advertise/', include('apps.advertise.urls')),
    url(r'^profiles/', include('apps.profiles.urls')),
    url(r'^cart/', include('apps.carts.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/profiles/urls.py
from django.conf.urls import url, include
from . import views as auth_views
from django.contrib.auth.views import (PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordResetDoneView, PasswordResetView)

patterns = [
    url(r'^login/$', auth_views.authenticate_view, name='login'),
    url(r'^sign-up/$', auth_views.UserCreationView.as_view(), name='sign_up'),
    url(r'^logout/$', auth_views.logout_view, name='logout'),
    url(r'^activation/$',auth_views.wait_activation, name='activation'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.activate, name='activate'),
    url(r'^my-advertises/$', auth_views.MyAdvertises.as_view(), name='my_advertises'),

]

urlpatterns = [
    url(r'^password-reset/$', PasswordResetView.as_view(
        template_name='profiles/password_reset.html'), name='password_reset'),
    url(r'^password-reset/done$', PasswordResetDoneView.as_view(
        template_name='profiles/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(
        template_name='profiles/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', PasswordResetCompleteView.as_view(
        template_name='profiles/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^my-profile/$', auth_views.profile, name='profile'),
    url(r'^', include(patterns, namespace='profiles')),
]

apps/profiles/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.utils.translation import ugettext_lazy as _

from apps.carts.models import Cart
from apps.utils.uuname import unique_username_generator

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=False, verbose_name=_('Active'))
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # extra fields

    def __str__(self):
        return self.user.email


def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.username:
        instance.username = unique_username_generator(instance)


def post_save_receiver(sender, instance,created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user=instance)
        cart, is_created = Cart.objects.get_or_create(user=instance)


pre_save.connect(pre_save_receiver, sender=User)
post_save.connect(post_save_receiver, sender=User)

apps/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class AuthenticationForm(forms.Form):
    email = forms.EmailField(max_length=254, label=_('Email'))
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput)


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    email = forms.EmailField(label=_('Email'), required=True, max_length=254)
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput, )

    class Meta:
        model = User
        fields = ()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

apps/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, ListView
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils.translation import ugettext as _

from apps.advertise.models import Advertise
from .tokens import profile_activation_token
from .forms import AuthenticationForm
from .forms import UserCreationForm


class UserCreationView(CreateView):
    form_class = UserCreationForm
    template_name = 'profiles/sign_up.html'
    success_url = reverse_lazy('profiles:activation')

    def form_valid(self, form):
        user = form.save()
        current_site = get_current_site(self.request)
        mail_subject = 'اکانت خود را فعال کنید.'
        message = render_to_string('profiles/activate_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
            'token': profile_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(
            mail_subject, message, to=[to_email]
        )
        email.send()
        messages.add_message(self.request, messages.SUCCESS,
                             'لطفا اقدام به فعال سازی ایمیل خود کنید.')
        return super().form_valid(form)


def authenticate_view(request):
    template_name = 'profiles/login.html'
    form = AuthenticationForm(request.POST or None)
    errors = []
    if request.method == "POST":
        if form.is_valid():
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            if not user.profile.active:
                errors.append("لطفا اقدام به فعالسازی اکانت خود کنید")
            else:
                username = user.username
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect(reverse('advertise:list'))

                else:
                    errors.append("کاربر موجود نیست")
        else:
            errors.append("اطلاعات وارد شده معتبر نیست")

    return render(request, template_name, context={'form': form, 'errors': errors})


def logout_view(request):
    logout(request)
    return redirect('advertise:list')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and profile_activation_token.check_token(user, token):
        user.profile.active = True
        user.profile.save()
        messages.add_message(request, messages.SUCCESS, _('Your account email successfully activated.'))
        return redirect(reverse('profiles:login'))

    else:
        messages.add_message(request, messages.ERROR, _('Activation link is invalid!'))
        return redirect(reverse('advertise:list'))


def wait_activation(request):
    return render(request, 'profiles/wait_activation.html')


class MyAdvertises(LoginRequiredMixin, ListView):
    template_name = "profiles/my_advertises.html"
    context_object_name = "advertises"

    def get_queryset(self):
        return Advertise.objects.filter(user=self.request.user)


@login_required
def profile(request):
    return render(request, 'profiles/profile.html')

apps/profiles/templates/profiles/activate_email.html
{% autoescape off %}
Hi {{ user.email }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'profiles:activate' uidb64=uid token=token %}
{% endautoescape %}

apps/profiles/templates/profiles/login.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load semanticui %}{% load i18n %}

{% block body %}
<div class="ui text container" style="margin: 30px;">
    {% for error in errors %}
    <p>{{ error }}</p>
    {% endfor %}


    <div class="ui attached message">
        <div class="header">
            خوش آمدید
        </div>
    </div>
    <form class="ui form attached fluid segment" role="form" method="post" action="{% url 'profiles:login' %}">
    {% csrf_token %}
    {{ form|semanticui_form }}

        <input type="submit" class="ui blue button" value="{% trans 'Login' %}">
        <input type="hidden" name="next" value="{{ next }}">
        <div class="ui error message"></div>
    </form>

    <div class="ui bottom attached warning message">
        <a href="{% url 'password_reset' %}">رمز عبور را فراموش کرده اید؟</a>
    </div>
</div>
<script>

    // ready event
    readyV = function() {

        // selector cache
        var
            $form = $('.ui.form'),
            // alias
            handler
        ;

        // event handlers
        handler = {

        };


        $.fn.form.settings.defaults = {
            email: {
                identifier : 'email',
                rules: [
                    {
                        type   : 'empty',
                        prompt : 'ایمیل را وارد کنید'
                    },
                    {
                        type   : 'regExp',
                        value: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
                        prompt : 'یک ایمیل معتبر وارد کنید'
                    }
                ]
            },
            password: {
                identifier : 'password',
                rules: [
                    {
                        type   : 'empty',
                        prompt : 'گذرواژه را وارد کنید'
                    },
                    {
                        type   : 'length[8]',
                        prompt : 'گذرواژه حداقل باید دارای ۸ کاراکتر باشد'
                    }
                ]
            }
        };


        $form
            .form({
                inline : true,
                on: 'blur'
            })
        ;

    };
    // attach ready event
    $(document)
        .ready(readyV)
    ;
</script>
{% endblock %}

apps/profiles/templates/profiles/my_advertises.html
{% extends 'amoo-jozve-foroosh/base.html' %}
{% block body %}
    <div class="ui container">
        <h2 class="ui header" style="padding: 20px;">آگهی‌های من</h2>
        <div class="ui special cards">
            {% for advertise in advertises %}
                {% include 'advertise/snippets/advertise_card.html' with advertise=advertise %}
            {% endfor %}
        </div>
        <div style="text-align: center; margin-top: 15px    ">
            {% include 'amoo-jozve-foroosh/pagination.html' with page_obj=page_obj %}
        </div>
    </div>
{% endblock body %}

apps/profiles/templates/profiles/password_reset.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load semanticui %}{% load i18n %}
{% block body %}
<div class="ui text container" style="margin: 30px;">
    <div class="ui attached message">
        <div class="header">
            رمز عبور خود را فراموش کرده اید؟
        </div>
        <p>آدرس ایمیل خود را وارد کنید تا دستورات لازم را به آن ارسال کنیم.</p>
    </div>

    <form class="ui form attached fluid segment" role="form" method="POST">
        {% csrf_token %}
        {{ form|semanticui_form}}
        <input class="ui blue button" type="submit" value="{% trans 'Send' %}">
    </form>
</div>
<script>

    // ready event
    readyV = function () {

        // selector cache
        var
            $form = $('.ui.form'),
            // alias
            handler
        ;

        // event handlers
        handler = {};


        $.fn.form.settings.defaults = {
            email: {
                identifier: 'email',
                rules: [
                    {
                        type: 'empty',
                        prompt: 'ایمیل را وارد کنید'
                    },
                    {
                        type: 'regExp',
                        value: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
                        prompt: 'یک ایمیل معتبر وارد کنید'
                    }
                ]
            }
        };


        $form
            .form({
                inline: true,
                on: 'blur'
            })
        ;

    };
    // attach ready event
    $(document)
        .ready(readyV)
    ;
</script>
{% endblock body %}

apps/profiles/templates/profiles/password_reset_complete.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load semanticui %}{% load i18n %}
{% block body %}
    <div class="ui center aligned text container" style="margin: 30px;">
        <div class="ui success message">
            <h1>رمز عبور ریست شد</h1>
            <p><a href="{% url 'profiles:login' %}">{% trans 'Login' %}</a></p>
        </div>
    </div>
{% endblock body %}

apps/profiles/templates/profiles/password_reset_confirm.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load semanticui %}{% load i18n %}
{% block body %}
<div class="ui text container" style="margin: 30px;">
    <div class="ui attached message">
        <div class="header">
            رمز عبور جدید را وارد کنید
        </div>
    </div>
    <form class="ui form attached fluid segment" role="form" method="POST">
        {% csrf_token %}
        {{ form|semanticui_form }}
        <input class="ui blue button" type="submit" value="{% trans 'Ok' %}">
    </form>
</div>
<script>
    $(document).ready(function () {
        $('.ui.form').form({
            inline: true,
            fields: {
                new_password1: {
                    identifier: 'new_password1',
                    rules: [
                        {
                            type: 'empty',
                            prompt: 'گذرواژه را وارد کنید'
                        },
                        {
                            type: 'length[8]',
                            prompt: 'گذرواژه حداقل باید دارای ۸ کاراکتر باشد'
                        }
                    ]
                },
                new_password2: {
                    identifier: 'new_password2',
                    rules: [
                        {
                            type: 'empty',
                            prompt: 'گذرواژه را تکرار کنید'
                        },
                        {
                            type: 'match[new_password1]',
                            prompt: 'گذرواژه همخوانی ندارد'
                        }
                    ]
                }
            }
        });
    });
</script>
{% endblock body %}

apps/profiles/templates/profiles/password_reset_done.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load semanticui %}{% load i18n %}
{% block body %}
    <div class="ui center aligned text container">
        <div class="ui success message">
            <h1> صندوق ورودی ایمیل خود را بررسی کنید</h1>
            <p>دستورات لازم برای ریست کردن رمزعبور برای شما ارسال شد.</p>
        </div>
    </div>
{% endblock body %}

apps/profiles/templates/profiles/profile.html
{% extends 'amoo-jozve-foroosh/base.html' %}

{% block extra_header %}
    <style>
        .ui.submitBtn {
            margin-bottom: 2em;
            margin-top: 2em;
        }

        .ui.profTab {
            margin: 0;
            padding: 0;
        }

        .iconBackground {
            background-color: #F8F8F8;
            border-bottom: 1px solid #00B5AD;
            height: 10em;
            margin: 0;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="ui stackable mobile grid container" style="margin-top: 3em">
        <div class="four wide column">
            <div class="ui vertical large menu">
                <a class="pink item active" data-tab="userInfo">
                    اطلاعات کاربری
                    <i class="ui user outline icon" style="float: right; margin-left: 1em; margin-right: 0"></i>
                </a>
                <a class="pink item" data-tab="userAdvertises">
                    <i class="ui file alternate outline icon"
                       style="float: right; margin-left: 1em; margin-right: 0"></i>
                    آگهی های من
                </a>
                <a class="pink item" data-tab="resetPass">
                    <i class="ui key icon" style="float: right; margin-left: 1em; margin-right: 0"></i>
                    تغییر رمز عبور
                </a>
            </div>
        </div>
        <div class="twelve wide column">
            <div class="ui active transition fade in tab center aligned segment profTab" data-tab="userInfo">
                <div class="iconBackground"></div>
                <i class="teal circular inverted massive user icon" style="margin-top: -1em"></i>
                <h3 class="centered" style="color: dimgrey">اطلاعات کاربری</h3>
                <div class="ui divider" style="margin-bottom: 3em;margin-top: 5em"></div>
                <div class="ui form" style="margin-left: 5em; margin-right: 5em">
                    <div class="two fields">
                        <div class="field">
                            <div class="ui left icon input">
                                <input type="text" placeholder="نام">
                                <i class="user teal icon"></i>
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui left icon input">
                                <input type="text" placeholder="نام خانوادگی">
                                <i class="user circle teal icon"></i>
                            </div>
                        </div>
                    </div>
                    <div class="two fields">
                        <div class="field">
                            <div class="ui left icon input">
                                <input type="text" placeholder="شماره تماس">
                                <i class="phone green icon"></i>
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui left icon input">
                                <input type="text" placeholder="ایمیل">
                                <i class="mail yellow icon"></i>
                            </div>
                        </div>
                    </div>
                    <button class="ui positive button submitBtn" type="submit">ثبت تغییرات</button>
                </div>
            </div>
            <div class="ui transition fade in tab center aligned segment profTab" data-tab="userAdvertises">
                <div class="iconBackground"></div>
                <i class="teal inverted circular massive file alternate outline icon" style="margin-top: -1em"></i>
                <h3 style="color: dimgrey">آگهی های من</h3>
                <div class="ui divider" style="margin-bottom: 3em;margin-top: 5em"></div>
            </div>
            <div class="ui transition fade in tab center aligned segment profTab" data-tab="resetPass">
                <div class="iconBackground"></div>
                <i class="teal inverted circular massive key icon" style="margin-top: -1em"></i>
                <h3 style="color: dimgrey">تغییر رمز عبور</h3>
                <div class="ui divider" style="margin-bottom: 3em;margin-top: 5em"></div>
                <form class="ui form" style="margin-left: 15em; margin-right: 15em">
                    <div class="field">
                        <label style="font-size: 1em">رمز عبور فعلی</label>
                        <input id="pervPass" type="password" style="text-align: center">
                    </div>
                    <div class="field">
                        <label style="font-size: 1em">رمز عبور جدید</label>
                        <input id="newPass" type="password" style="text-align: center">
                    </div>
                    <div class="field">
                        <label style="font-size: 1em">تکرار رمز عبور جدید</label>
                        <input id="newPassRepeat" type="password" style="text-align: center">
                    </div>
                    <button class="ui positive button submitBtn" type="submit">ثبت تغییرات</button>
                </form>
            </div>
        </div>
    </div>

    <script src="jquery.min.js"></script>
    <script
            src="https://cdn.rtlcss.com/semantic-ui/2.4.1/semantic.min.js"
            integrity="sha384-6urqf2sgCGDfIXcoxTUOVIoQV+jFr/Zuc4O2wCRS6Rnd8w0OJ17C4Oo3PuXu8ZtF"
            crossorigin="anonymous"></script>
    <script>
        $('.menu .item').tab();
    </script>
    
{% endblock body %}

apps/profiles/templates/profiles/sign_up.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load semanticui %}{% load i18n %}

{% block body %}
<div class="ui text container" style="margin: 30px;">

    <form class="ui form segment" role="form" method="post" action="{% url 'profiles:sign_up' %}">
        {% csrf_token %}
        {{ form|semanticui_form }}

        <input type="submit" class="ui blue button" value="{% trans 'Sign_up' %}">
        <a href="{% url 'profiles:login' %}">حساب کاربری دارید؟</a>
        <input type="hidden" name="next" value="{{ next }}">
    </form>

</div>
<script>

    // ready event
    readyV = function() {

        // selector cache
        var
            $form = $('.ui.form'),
            // alias
            handler
        ;

        // event handlers
        handler = {

        };


        $.fn.form.settings.defaults = {
            email: {
                identifier : 'email',
                rules: [
                    {
                        type   : 'empty',
                        prompt : 'ایمیل را وارد کنید'
                    },
                    {
                        type   : 'regExp',
                        value: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
                        prompt : 'یک ایمیل معتبر وارد کنید'
                    }
                ]
            },
            password1: {
                identifier : 'password1',
                rules: [
                    {
                        type   : 'empty',
                        prompt : 'گذرواژه را وارد کنید'
                    },
                    {
                        type   : 'length[8]',
                        prompt : 'گذرواژه حداقل باید دارای ۸ کاراکتر باشد'
                    }
                ]
            },
            password2: {
                identifier : 'password2',
                rules: [
                    {
                        type   : 'empty',
                        prompt : 'گذرواژه را تکرار کنید'
                    },
                    {
                        type   : 'match[password1]',
                        prompt : 'گذرواژه همخوانی ندارد'
                    }
                ]
            }
        };


        $form
            .form({
                inline : true,
                on: 'blur'
            })
        ;

    };
    // attach ready event
    $(document)
        .ready(readyV)
    ;
</script>
{% endblock %}

apps/profiles/templates/profiles/wait_activation.html
{% extends 'amoo-jozve-foroosh/base.html' %}

{% block body %}
    <div class="ui center aligned text container">
        <div class="ui success message">
            <p>ایمیل فعال سازی حساب کاربری برای شما فرستاده شد.
                <br/>
                صندوق ورودی خود را بررسی کنید.
            </p>
        </div>
    </div>
{% endblock %}