AmooJozveForoosh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('apps.landpage.urls', namespace='landpage')),
    url(r'^admin/', admin.site.urls),
    url(r'^advertise/', include('apps.advertise.urls')),
    url(r'^profiles/', include('apps.profiles.urls')),
    url(r'^cart/', include('apps.carts.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/advertise/urls.py
from django.conf.urls import url
from . import views

app_name = 'advertise'
urlpatterns = [
    url(r'^$', views.AdvertiseListView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', views.AdvertiseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.AddAdvertise.as_view(), name='add_advertise'),
    url(r'^(?P<pk>[0-9]+)/add-comment/$', views.CommentCreateView.as_view(), name='add_comment'),
    url(r'^ajax/filter-counties/$', views.filter_cities, name='filter-counties'),
    url(r'^rating/(?P<advertise_id>\d+)/$', views.rating, name='rating')
]

apps/advertise/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Province(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('Province name'))

    def __str__(self):
        return self.name


class County(models.Model):
    province = models.ForeignKey(Province, related_name="counties", verbose_name=_('Province'),
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=30, verbose_name=_('County name'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Counties'


class University(models.Model):
    county = models.ForeignKey(County, on_delete=models.CASCADE, verbose_name=_('County'),
                               related_name='universities')
    name = models.CharField(max_length=50, verbose_name=_('university name'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Universities'


class Advertise(models.Model):
    PUBLIC = 'P'
    MAJOR_CHOICES = (
        (PUBLIC, _('Public')),
        ('CE', _('Computer Engineering')),
        ('EE', _('Electrical Engineering')),
    )

    PENDING = 'P'
    PUBLISHED = 'PB'
    CLOSED = 'C'
    STATE_CHOICES = (
        (PENDING, _('Pending')),
        (PUBLISHED, _('Published')),
        (CLOSED, _('Closed')),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('User'))
    county = models.ForeignKey(County, on_delete=models.SET_NULL, null=True, verbose_name=_('County'))
    university = models.ForeignKey(University, on_delete=models.SET_NULL, verbose_name=_('University'),
                                   blank=True, null=True)
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    description = models.TextField(max_length=2000, verbose_name=_('Description'))
    expiration_date = models.DateTimeField(blank=True, null=True,
                                           verbose_name=_('Expiration date'))  # null = never expire
    price = models.PositiveIntegerField(verbose_name=_('Price'))
    major = models.CharField(max_length=10, choices=MAJOR_CHOICES, default=PUBLIC, verbose_name=_('Major'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))
    state = models.CharField(max_length=10, choices=STATE_CHOICES, default=PENDING, verbose_name=_('State'))
    page_numbers = models.PositiveIntegerField(null=True, blank=True, verbose_name=_('Page numbers'))
    publisher = models.CharField(max_length=100, null=True, blank=True, verbose_name=_('Publisher'))
    release_year = models.CharField(max_length=4, null=True, blank=True, verbose_name=_('Release year'))

    def __str__(self):
        return self.title


class AdvertiseImage(models.Model):
    ADVERTISE_IMAGE_UPLOAD_PATH = 'advertise/images'
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=ADVERTISE_IMAGE_UPLOAD_PATH, verbose_name=_('Advertise image'))

    def __str__(self):
        return self.advertise.title


class Comment(models.Model):
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='comments', null=True)
    text = models.TextField(verbose_name=_('Text'), max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    def approve(self):
        self.approved = True
        self.save()


class Rate(models.Model):
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.SmallIntegerField(validators=[MaxValueValidator(5)])

    def __str__(self):
        return "{} - {} - {}".format(self.advertise.title, self.user.email, self.rate)

apps/advertise/forms.py
from django import forms
from django.forms import inlineformset_factory

from semanticuiform.widgets import SemanticSearchSelect

from apps.advertise.models import County, AdvertiseImage, Comment
from .models import Advertise


class AdvertiseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        if not kwargs.get('data'):
            self.fields['county'].queryset = County.objects.none()

    class Meta:
        model = Advertise
        exclude = ('user', 'state', 'expiration_date')
        widgets = {
            'major': SemanticSearchSelect,
            'county': SemanticSearchSelect,
            'university': SemanticSearchSelect,
        }


class AdvertiseImageForm(forms.ModelForm):
    class Meta:
        model = AdvertiseImage
        fields = ('image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )


AdvertiseImageFormSet = inlineformset_factory(Advertise, AdvertiseImage, form=AdvertiseImageForm, extra=1,
                                              can_delete=True)

apps/advertise/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, FormView, CreateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render, get_object_or_404

from apps.advertise.forms import CommentForm
from apps.advertise.models import Province, County, University, Comment, Rate
from apps.utils.decorators import require_ajax
from .models import Advertise
from .forms import AdvertiseForm, AdvertiseImageFormSet


class AdvertiseListView(ListView):
    template_name = 'advertise/advertise_list.html'
    paginate_by = 12

    def get_queryset(self):
        major = self.request.GET.get('major')
        university = self.request.GET.get('university')
        province = self.request.GET.get('province')
        county = self.request.GET.get('county')

        qs = Advertise.objects.all()
        if major:
            qs = qs.filter(major=major)
        if university:
            university = int(university)
            qs = qs.filter(university__id=university)
        if not county:
            if province:
                province = int(province)
                qs = qs.filter(county__province__id=province)
        if county:
            county = int(county)
            qs = qs.filter(county__id=county)
        return qs.filter(state=Advertise.PUBLISHED).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['majors'] = Advertise.MAJOR_CHOICES
        context['universities'] = University.objects.all()
        context['provinces'] = Province.objects.all()
        context['counties'] = County.objects.none()
        return context


class AdvertiseDetailView(DetailView):
    template_name = 'advertise/advertise_detail.html'
    model = Advertise

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm(None)
        context['comments'] = Comment.objects.filter(advertise__id=self.get_object().pk).order_by('-timestamp')
        if self.request.user.is_authenticated:
            context['rate'] = Rate.objects.filter(user=self.request.user, advertise=self.get_object())
        sum_rating = Rate.objects.filter(advertise=self.get_object()).aggregate(rating=Sum('rate')).get('rating')
        sum_count = Rate.objects.filter(advertise=self.get_object()).count()
        if not sum_count:
            sum_rating = 0
            sum_count = 1
        context['rating'] = sum_rating // sum_count
        return context


def filter_cities(request):
    if request.method == "GET" and request.is_ajax():
        province = request.GET.get('province')
        if province:
            response = {}
            data = County.objects.filter(province__id=int(province))
            for county in data:
                response[county.id] = {'id': county.id, 'name': county.name}
            return JsonResponse(response)
        return JsonResponse({"message": "Invalid province"})


class AddAdvertise(LoginRequiredMixin, FormView):
    template_name = 'advertise/new_advertise.html'
    form_class = AdvertiseForm
    success_url = reverse_lazy('advertise:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['provinces'] = Province.objects.all()
        if self.request.POST:
            context['image_formset'] = AdvertiseImageFormSet(self.request.POST, self.request.FILES)
        else:
            context['image_formset'] = AdvertiseImageFormSet()
        return context

    def form_valid(self, form):
        advertise = form.save(commit=False)
        advertise.user = self.request.user
        advertise.state = Advertise.PENDING
        advertise.save()
        context = self.get_context_data()
        advertise_image_formset = context['image_formset']
        advertise_image_formset.instance = advertise
        for form in advertise_image_formset.forms:
            if form.is_valid():
                image = form.save(commit=False)
                image.advertise = advertise
                image.save()
        messages.add_message(self.request, messages.SUCCESS, _('Advertise added successfully.'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, _('Please correct the following errors.'))
        return super().form_invalid(form)


class CommentCreateView(LoginRequiredMixin, FormView):
    form_class = CommentForm

    def get_success_url(self):
        return reverse('advertise:detail', args=(self.kwargs.get('pk'),))

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.advertise = Advertise.objects.get(pk=int(self.kwargs.get('pk')))
        comment.save()
        messages.add_message(self.request, messages.SUCCESS, _('Your comment successfully added.'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, _('Please correct the following errors.'))
        return super().form_invalid(form)


@login_required
@require_ajax
def rating(request, advertise_id):
    advertise = get_object_or_404(Advertise, id=advertise_id)
    rate = request.POST.get('rate')
    if not Rate.objects.filter(advertise=advertise, user=request.user).exists():
        Rate.objects.create(advertise=advertise, user=request.user, rate=rate)
        return JsonResponse({'status': 'ok'})
    else:
        return JsonResponse({'status': 'ko'})

apps/advertise/templates/advertise/advertise_detail.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load staticfiles %}{% load amoo_extras %}{% load i18n %}{% load semanticui %}
{% block head_title %}
    {{ object.title }}
{% endblock %}
{% block extra_header %}
    <script src="{% static 'vendor/clipboard/clipboard.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'vendor/bxslider/bxslider.min.css' %}">
    <script src="{% static 'vendor/bxslider/bxslider.min.js' %}"></script>
    <link rel="stylesheet" href="{% static "css/rating.min.css" %}">
    <script type="text/javascript" src="{% static "js/rating.min.js" %}"></script>
{% endblock %}
{% block body %}
    <div class="ui container" style="padding-top: 30px">
        <div class="ui stackable two column mobile reversed grid">
            <div class="ui column">
                <h1 id="productName" class="ui header">{{ object.title }}</h1>
                <button id="showInfoBtn" onclick="showSellerInfo()" class="ui red button">
                    دریافت اطلاعات فروشنده
                </button>
                <div class="ui middle aligned divided large relaxed list">
                    <div id="sellerInfo" class="item" style="display: none">
                        <div class="right floated content">
                            <div class="ui mini input">
                                <input type="text" value="۰۹۳۰۱۲۳۶۵۴۸۷۹" readonly id="phone"/>
                            </div>
                            <button class="ui small basic button" id="phone-cp-btn" data-clipboard-target="#phone">
                                کپی
                            </button>
                            <div class="ui mini top center popup transition hidden" id="cp-popup">
                                {% trans 'Copied!' %}
                            </div>
                        </div>
                        <div class="content">
                            شماره تماس
                        </div>
                    </div>
                    <div class="item">
                        <div class="right floated content">
                            {{ object.get_major_display }}
                        </div>
                        <div class="content">
                            رشته
                        </div>
                    </div>
                    {% if object.university %}
                        <div class="item">
                            <div class="right floated content">
                                {{ object.university }}
                            </div>
                            <div class="content">
                                دانشگاه
                            </div>
                        </div>
                    {% endif %}
                    <div class="item">
                        <div class="right floated content">
                            {{ object.county.province.name }} - {{ object.county.name }}
                        </div>
                        <div class="content">
                            محل
                        </div>
                    </div>
                    <div class="item">
                        <div class="right floated content">
                            {{ object.price|persian_digits }}
                        </div>
                        <div class="content">
                            قیمت
                        </div>
                    </div>
                    {% if object.page_numbers is not None %}
                        <div class="item">
                            <div class="right floated content">
                                {{ object.page_numbers|persian_digits }}
                            </div>
                            <div class="content">
                                تعداد صفحات
                            </div>
                        </div>
                    {% endif %}
                    <div class="item">
                        <div class="right floated content">
                            <div class='ui star rating' id="itemRate"></div>
                        </div>
                        <div class="content">
                            امتیاز کاربران
                        </div>
                    </div>
                    <br/><br/>
                    توضیحات

                    <p id="details">
                        {{ object.description }}
                    </p>
                </div>
                <div class="ui stackable two column mobile reversed grid">
                    <div class="ui row">
                        {% if request.user.is_authenticated %}
                            {% if not rate %}
                                <div class="ui left floated column">
                                    <div id="rate" class='ui left floated star rating' style="display: none;"></div>
                                </div>
                                <div class="ui right floated column" style="padding: 0">
                                    <div id="rate-btn" class="ui right floated red icon basic button"
                                         onclick="showRating()">
                                        <i class="star icon"></i> امتیاز دهید
                                    </div>
                                </div>
                            {% else %}
                                <div class="ui left floated column">
                                    امتیاز شما:
                                    <div id="rate" class='ui left floated star rating'></div>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="bxslider" id="slider">
                    {% for img in object.advertiseimage_set.all %}
                        <div class="ui centered image"><img class="ui image" src={{ img.image.url }}></div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <br/>
        <br/>
        <div class="ui comments">
            <h3 class="ui dividing header">نظرات</h3>
            {% for cm in comments %}
                {% include 'advertise/snippets/comment.html' with cm=cm %}
            {% endfor %}
            {% if request.user.is_authenticated %}
                <form class="ui form" role="form" method="post"
                      action="{% url 'advertise:add_comment' pk=object.id %}"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|semanticui_form }}
                    <button type="submit" class="ui blue button">{% trans 'Add' %}</button>
                </form>
            {% endif %}
        </div>
    </div>
    <script>
        function showSellerInfo() {
            $('#sellerInfo').css('display', 'block');
            $("#showInfoBtn").addClass('disabled');
        }

        $(document).ready(function () {
            let cb = new ClipboardJS('#phone-cp-btn');
            $('#phone-cp-btn').popup({popup: $("#cp-popup"), on: 'click'});

            $('.bxslider').bxSlider({
                mode: 'fade',
                auto: true,
                stopAutoOnClick: true,
                slideWidth: parent
            });
        })
    </script>
    <script>
        $('.bxslider').bxSlider({
            mode: 'fade',
            auto: true,
            stopAutoOnClick: true,
            slideWidth: parent
        });
    </script>
    <script>
        $('#itemRate').rating({
            initialRating: {{ rating|default_if_none:0 }},
            maxRating: 5,
        });
        $('#itemRate')
            .rating('disable');
    </script>
    <script>
        function showRating() {
            {% if not rate %}
                document.getElementById("rate").style.display = "inline";
                $('#rate')
                    .rating(
                        {
                            initialRating: 0,
                            maxRating: 5,
                            onRate: function (value) {
                                $.ajax({
                                    type: "POST",
                                    url: "{% url 'advertise:rating' advertise.id %}",
                                    data: {
                                        rate: value,
                                        csrfmiddlewaretoken: '{{ csrf_token }}'
                                    },
                                    success: function () {
                                        $('#rate')
                                            .rating('disable');
                                        $('#rate-btn').css('display', 'none')
                                    }
                                });
                            }
                        });
            {% endif %}
        }
        {% if rate %}
            document.getElementById("rate").style.display = "inline";
            $('#rate')
                .rating(
                    {
                        initialRating: {{ rate.first.rate }},
                        maxRating: 5
                    });
            $('#rate')
                .rating('disable');


        {% endif %}
    </script>
{% endblock body %}

apps/advertise/templates/advertise/advertise_list.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load staticfiles %}{% load i18n %}
{% block body %}
    <div class="ui container">
        <div class="ui very relaxed stackable grid">
            {% comment %}
            <div class="three wide column">
                <div class="ui vertical menu">
                    <a href="#" class="active item">همه</a>
                    <a href="#" class="item">ریاضی</a>
                    <a href="#" class="item">فیزیک</a>
                    <a href="#" class="item">شیمی</a>
                    <a href="#" class="item">کامپیوتر</a>
                    <a href="#" class="item">اقتصاد</a>
                    <a href="#" class="item">ادبیات</a>
                    <a href="#" class="item">معارف</a>
                </div>
            </div>
            {% endcomment %}
            <div class="sixteen wide column">
                <div class="ui segment" style="display: inline-block">
                    <form action="." class="ui form">
                        <div class="three fields">
                            <div class="field">
                                <div class="ui search selection dropdown" id="province-dropdown">
                                    <input type="hidden" name="province" id="province-id">

                                    <div class="default text">انتخاب استان</div>
                                    <div class="menu">

                                        {% for province in provinces %}
                                            <div class="item" data-value="{{ province.id }}">{{ province.name }}</div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>

                            <div class="field">
                                <div class="ui search selection dropdown" id="county-dropdown">
                                    <input type="hidden" name="county">
                                    <div class="default text">انتخاب شهر</div>
                                    <div class="menu" id="county-options">

                                        {% for county in counties %}
                                            <div class="item" data-value="{{ county.id }}">{{ county.name }}</div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>

                            <div class="field">
                                <div class="ui search selection dropdown" id="major-dropdown">
                                    <input type="hidden" name="major">
                                    <div class="default text">انتخاب رشته</div>
                                    <div class="menu">

                                        {% for major in majors %}
                                            <div class="item" data-value="{{ major.0 }}">{{ major.1 }}</div>
                                        {% endfor %}
                                    </div>

                                </div>
                            </div>

                            <div class="field">
                                <div class="ui search selection dropdown" id="university-dropdown">
                                    <input type="hidden" name="university">
                                    <div class="default text">انتخاب دانشگاه</div>
                                    <div class="menu transition">
                                        {% for university in universities %}
                                            <div class="item"
                                                 data-value="{{ university.id }}">{{ university.name }}</div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="field">
                                <button class="ui blue button" type="submit">جستجو</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="ui hidden divider"></div>
                <div class="ui special cards">
                    {% for advertise in object_list %}
                        {% include 'advertise/snippets/advertise_card.html' with advertise=advertise %}
                    {% endfor %}
                </div>
                <div style="text-align: center; margin-top: 15px    ">
                    {% include 'amoo-jozve-foroosh/pagination.html' with page_obj=page_obj %}
                </div>
            </div>
        </div>
    </div>
    <script>
        $("#major-dropdown").dropdown({clearable: true});
        $("#university-dropdown").dropdown({clearable: true});
        $("#county-dropdown").dropdown({clearable: true});
        $("#province-dropdown").dropdown({clearable: true});
    </script>
    <script>
        $(document).ready(function () {
            $("#province-id").change(function () {
                var province = $('#province-id').val();
                var countyOptions = $('#county-options');
                countyOptions.empty();

                $.ajax({
                    url: '{% url 'advertise:filter-counties' %}',
                    data: {
                        'province': province
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data) {
                            $('#county-dropdown').dropdown('clear');
                            $.each(data, function (index, element) {
                                var option = '<div class="item" data-value=' + element.id + '>' + element.name + '</div>';
                                countyOptions.append(option);
                            });
                        }
                    }
                });

            });
        });
    </script>
{% endblock %}

apps/advertise/templates/advertise/new_advertise.html
{% extends 'amoo-jozve-foroosh/base.html' %}{% load semanticui %}{% load i18n %}{% load static %}

{% block extra_header %}
    {{ block.super }}
    <script src="{% static 'vendor/jquery-formset.js' %}"></script>
{% endblock %}
{% block body %}


    <div class="ui text container" style="margin: 30px;">


        <h1 class="ui header">
            {% trans 'New advertise' %}
        </h1>


        <div class="required field">
            <label for="id_county">استان</label>
            <div class="ui search selection dropdown" id="province-dropdown" style="width: 100%;">
                <input type="hidden" id="province-id">

                <div class="default text">انتخاب استان</div>
                <div class="menu">

                    {% for province in provinces %}
                        <div class="item" data-value="{{ province.id }}">{{ province.name }}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <br/>
        <form class="ui form" role="form" method="post" action="{% url 'advertise:add_advertise' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|semanticui_form }}
            {{ image_formset.management_form }}
            {% for form in image_formset %}
                <div class="inline two fields" id="image-formset">
                    {{ form|semanticui_form }}
                </div>
            {% endfor %}
            <br/>
            <br/>
            <button type="submit" class="ui blue button">{% trans 'Add' %}</button>
        </form>
    </div>

    <script>
        $("#province-dropdown").dropdown({clearable: true});
    </script>
    <script>
        $(document).ready(function () {
            $("#province-id").change(function () {
                var province = $('#province-id').val();
                var countyOptions = $('#id_county');
                countyOptions.empty();

                $.ajax({
                    url: '{% url 'advertise:filter-counties' %}',
                    data: {
                        'province': province
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data) {
                            $('#id_county').dropdown('clear');
                            countyOptions.append(new Option('---------', ''));
                            $.each(data, function (index, element) {
                                var option = new Option(element.name, element.id);
                                countyOptions.append(option);
                            });
                        }
                    }
                });

            });

            $('#image-formset').formset({
                prefix: '{{ image_formset.prefix }}',
                addText: '{% trans 'Add another image' %}',
                deleteText: '{% trans 'Delete image' %}',
            });
        });
    </script>
{% endblock %}