AmooJozveForoosh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('apps.landpage.urls', namespace='landpage')),
    url(r'^admin/', admin.site.urls),
    url(r'^advertise/', include('apps.advertise.urls')),
    url(r'^profiles/', include('apps.profiles.urls')),
    url(r'^cart/', include('apps.carts.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/advertise/urls.py
from django.conf.urls import url
from . import views

app_name = 'advertise'
urlpatterns = [
    url(r'^$', views.AdvertiseListView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', views.AdvertiseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.AddAdvertise.as_view(), name='add_advertise'),
    url(r'^(?P<pk>[0-9]+)/add-comment/$', views.CommentCreateView.as_view(), name='add_comment'),
    url(r'^ajax/filter-counties/$', views.filter_cities, name='filter-counties'),
    url(r'^rating/(?P<advertise_id>\d+)/$', views.rating, name='rating')
]

apps/carts/urls.py
from django.conf.urls import url
from . import views

app_name = 'carts'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.CartDetailView.as_view(), name='detail'),
    url(r'^add-to-cart/$', views.CartCreateView.as_view(), name='add_to_cart'),
    url(r'^remove-from-cart/$', views.CartRemoveView.as_view(), name='remove_from_cart'),
]

apps/profiles/urls.py
from django.conf.urls import url, include
from . import views as auth_views
from django.contrib.auth.views import (PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordResetDoneView, PasswordResetView)

patterns = [
    url(r'^login/$', auth_views.authenticate_view, name='login'),
    url(r'^sign-up/$', auth_views.UserCreationView.as_view(), name='sign_up'),
    url(r'^logout/$', auth_views.logout_view, name='logout'),
    url(r'^activation/$',auth_views.wait_activation, name='activation'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.activate, name='activate'),
    url(r'^my-advertises/$', auth_views.MyAdvertises.as_view(), name='my_advertises'),

]

urlpatterns = [
    url(r'^password-reset/$', PasswordResetView.as_view(
        template_name='profiles/password_reset.html'), name='password_reset'),
    url(r'^password-reset/done$', PasswordResetDoneView.as_view(
        template_name='profiles/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(
        template_name='profiles/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', PasswordResetCompleteView.as_view(
        template_name='profiles/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^my-profile/$', auth_views.profile, name='profile'),
    url(r'^', include(patterns, namespace='profiles')),
]

templates/amoo-jozve-foroosh/top-bar/base.html
{% load staticfiles %}{% load i18n %}
<div class="ui borderless menu">
    <div class="ui fluid container">
        {% block logo %}
            <a href="{% url 'advertise:list' %}" class="item">
                <img src="{% static 'advertise/images/logo.png' %}"/>
            </a>
        {% endblock %}

        {% block menu-right %}{% endblock %}

        <div class="right menu">
            {% block menu-left %}{% endblock menu-left %}
            <div class="item">
                <a href="{% url 'advertise:add_advertise' %}" class="ui teal button">
                    {% trans 'New advertise' %}
                </a>
            </div>
        </div>
    </div>
</div>

templates/amoo-jozve-foroosh/top-bar/login.html
{% extends 'amoo-jozve-foroosh/top-bar/base.html' %}{% load amoo_extras %}

{% block menu-right %}
<a class="item" href="{% url 'profiles:my_advertises' %}">آگهی‌های من</a>
{# ui for cart icon here #}

<a class="item" href="{% url 'carts:detail' request.user.cart.id %}">
    <div class="ui grey labeled icon button">
        <i class="shopping cart icon"></i>
        <div class="detail">{{ request.user.cart.advertises.all.count|persian_digits }}</div>
    </div>
</a>

{% endblock %}

{% block menu-left %}
<a class="item" href="{% url 'profiles:logout' %}">خروج</a>
{% endblock %}

templates/amoo-jozve-foroosh/top-bar/logout.html
{% extends 'amoo-jozve-foroosh/top-bar/base.html' %}

{% block menu-right %}
    <a class="active item">صفحه من</a>
{% endblock %}

{% block menu-left %}
    <a class="item" href="{% url 'profiles:login' %}">ورود</a>
    <a class="item" href="{% url 'profiles:sign_up' %}">ثبت نام</a>
{% endblock %}

templates/amoo-jozve-foroosh/top-bar/top-bar.html
{% if request.user.is_authenticated %}
    {% include 'amoo-jozve-foroosh/top-bar/login.html' %}
{% else %}
    {% include 'amoo-jozve-foroosh/top-bar/logout.html' %}
{% endif %}